name: Run Process
on:
  issues:
    types: opened
concurrency: 'main'
jobs:
  job_1:
    # TODO authorize via github.event.issue.author_association
    runs-on: ubuntu-latest
    steps:
      - run: echo '${{ github.event.issue.author_association }}'

      - uses: stefanbuck/github-issue-praser@v3
        id: issue-parser
        with:
          template-path: .github/ISSUE_TEMPLATE/initiate.yml

      - run: echo '${{ steps.issue-parser.outputs.jsonString }}'

      # TODO run external process

      - run: gh issue close ${{ github.event.issue.id }} --comment "handed off to external process"
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
